// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      //throw UnsupportedError(
      //  'DefaultFirebaseOptions have not been configured for linux - '
      //  'you can reconfigure this by running the FlutterFire CLI again.',
      //);
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZaypyjbOqRqhtk8JMLTgQ9RiqNQ0r7WU',
    appId: '1:763661712803:web:a8ea79efa54ac9485f6e16',
    messagingSenderId: '763661712803',
    projectId: 'dentalai-977aa',
    authDomain: 'dentalai-977aa.firebaseapp.com',
    storageBucket: 'dentalai-977aa.appspot.com',
    measurementId: 'G-EQXKC39YC0',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDZaypyjbOqRqhtk8JMLTgQ9RiqNQ0r7WU',
    appId: '1:763661712803:web:a8ea79efa54ac9485f6e16',
    messagingSenderId: '763661712803',
    projectId: 'dentalai-977aa',
    authDomain: 'dentalai-977aa.firebaseapp.com',
    storageBucket: 'dentalai-977aa.appspot.com',
    measurementId: 'G-EQXKC39YC0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjpDKZwgoiwAHOMXYWtOMsWAjo5GjCqWA',
    appId: '1:763661712803:ios:fef4331640e711e15f6e16',
    messagingSenderId: '763661712803',
    projectId: 'dentalai-977aa',
    storageBucket: 'dentalai-977aa.appspot.com',
    iosBundleId: 'com.example.signIn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZaypyjbOqRqhtk8JMLTgQ9RiqNQ0r7WU',
    appId: '1:763661712803:web:43b675b861f695455f6e16',
    messagingSenderId: '763661712803',
    projectId: 'dentalai-977aa',
    authDomain: 'dentalai-977aa.firebaseapp.com',
    storageBucket: 'dentalai-977aa.appspot.com',
    measurementId: 'G-W9ZR3F60WZ',
  );
}
